name: Frontend - Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - application/frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.2]
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate build
        run: |
          npm install -g @angular/cli
          npm install
          ng build -prod
        env:
          CI: false
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET_NAME }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_ID }} --paths /
